package love.marblegate.flowingagonyreborn.config

import love.marblegate.flowingagonyreborn.util.getValue
import net.minecraftforge.common.ForgeConfigSpec

class EnchantmentConfig {
    companion object {
        var spec: ForgeConfigSpec
        private val builder = ForgeConfigSpec.Builder()
        var tradableConfig: TradableConfig
        var discoverableConfig: DiscoverableConfig
        var applyOnEnchantingTableConfig: ApplyOnEnchantingTableConfig
        var isTreasureConfig: IsTreasureConfig

        init {
            builder.push("tradeable")
            tradableConfig = TradableConfig
            builder.pop()

            builder.push("discoverable")
            discoverableConfig = DiscoverableConfig(builder)
            builder.pop()

            builder.push("applyOnEnchantingTable")
            applyOnEnchantingTableConfig = ApplyOnEnchantingTableConfig(builder)
            builder.pop()

            builder.push("isTreasure")
            isTreasureConfig = IsTreasureConfig(builder)
            builder.pop()

            spec = builder.build()
        }
    }

    object TradableConfig {
        val anEnchantedGoldenAppleADay by builder.define("anEnchantedGoldenAppleADay", true)
        val deathPunk by builder.define("deathPunk", true)
        val exoticHealer by builder.define("exoticHealer", true)
        val savorTheTasted by builder.define("savorTheTasted", true)
        val trickster by builder.define("trickster", true)
        val covertKnife by builder.define("covertKnife", true)
        val enviousKind by builder.define("enviousKind", true)
        val eyesore by builder.define("eyesore", true)
        val sourceOfEnvy by builder.define("sourceOfEnvy", true)
        val thornInFlesh by builder.define("thornInFlesh", true)
        val cleansingBeforeUsing by builder.define("cleansingBeforeUsing", true)
        val comeBackAtDusk by builder.define("comeBackAtDusk", true)
        val dirtyMoney by builder.define("dirtyMoney", true)
        val pilferageCreed by builder.define("pilferageCreed", true)
        val carefullyIdentified by builder.define("carefullyIdentified", true)
        val nimbleFinger by builder.define("nimbleFinger", true)
        val regularCustomerProgram by builder.define("regularCustomerProgram", true)
        val armorUp by builder.define("armorUp", true)
        val frivolousStep by builder.define("frivolousStep", true)
        val miraculousEscape by builder.define("miraculousEscape", true)
        val potentialBurst by builder.define("potentialBurst", true)
        val stubbornStep by builder.define("stubbornStep", true)
        val infectiousMalice by builder.define("infectiousMalice", true)
        val iSeeYouNow by builder.define("iSeeYouNow", true)
        val maliceOutbreak by builder.define("maliceOutbreak", true)
        val perceivedMalice by builder.define("perceivedMalice", true)
        val vengeance by builder.define("vengeance", true)
        val backAndFill by builder.define("backAndFill", true)
        val agonyScreamer by builder.define("agonyScreamer", true)
        val cuttingWatermelonDream by builder.define("cuttingWatermelonDream", true)
        val insanePoet by builder.define("insanePoet", true)
        val paperBrain by builder.define("paperBrain", true)
        val shockTherapy by builder.define("shockTherapy", true)
        val burningPhobia by builder.define("burningPhobia", true)
        val constrainedHeart by builder.define("constrainedHeart", true)
        val drowningPhobia by builder.define("drowningPhobia", true)
        val piercingFever by builder.define("piercingFever", true)
        val destructionWorship by builder.define("destructionWorship", true)
        val prayerOfPain by builder.define("prayerOfPain", true)
        val freshRevenge by builder.define("freshRevenge", true)
        val hatredBloodline by builder.define("hatredBloodline", true)
        val outrageousSpirit by builder.define("outrageousSpirit", true)
        val resentfulSoul by builder.define("resentfulSoul", true)
        val tooResentfulToDie by builder.define("tooResentfulToDie", true)
        val morirsDeathwish by builder.define("morirsDeathwish", true)
        val morirsLifebound by builder.define("morirsLifebound", true)
        val guidensRegret by builder.define("guidensRegret", true)
        val lastSweetDream by builder.define("lastSweetDream", true)
        val necessaryEvil by builder.define("necessaryEvil", true)
        val survivalRuse by builder.define("survivalRuse", true)
        val survivalShortcut by builder.define("survivalShortcut", true)
        val corruptedKindred by builder.define("corruptedKindred", true)
        val lightburnFungalParasitic by builder.define("lightburnFungalParasitic", true)
        val prototypeChaotic by builder.define("prototypeChaotic", true)
        val prototypeChaoticTypeBeta by builder.define("prototypeChaoticTypeBeta", true)
        val shadowborn by builder.define("shadowborn", true)
        val scholarOfOriginalSin by builder.define("scholarOfOriginalSin", true)
        val originalSinErosion by builder.define("originalSinErosion", true)
        val burialObject by builder.define("burialObject", true)
    }

    class DiscoverableConfig(
        builder: ForgeConfigSpec.Builder
    ) {
        val anEnchantedGoldenAppleADay by builder.define("anEnchantedGoldenAppleADay", true)
        val deathPunk by builder.define("deathPunk", true)
        val exoticHealer by builder.define("exoticHealer", true)
        val savorTheTasted by builder.define("savorTheTasted", true)
        val trickster by builder.define("trickster", true)
        val covertKnife by builder.define("covertKnife", true)
        val enviousKind by builder.define("enviousKind", true)
        val eyesore by builder.define("eyesore", true)
        val sourceOfEnvy by builder.define("sourceOfEnvy", true)
        val thornInFlesh by builder.define("thornInFlesh", true)
        val cleansingBeforeUsing by builder.define("cleansingBeforeUsing", true)
        val comeBackAtDusk by builder.define("comeBackAtDusk", true)
        val dirtyMoney by builder.define("dirtyMoney", true)
        val pilferageCreed by builder.define("pilferageCreed", true)
        val carefullyIdentified by builder.define("carefullyIdentified", true)
        val nimbleFinger by builder.define("nimbleFinger", true)
        val regularCustomerProgram by builder.define("regularCustomerProgram", true)
        val armorUp by builder.define("armorUp", true)
        val frivolousStep by builder.define("frivolousStep", true)
        val miraculousEscape by builder.define("miraculousEscape", true)
        val potentialBurst by builder.define("potentialBurst", true)
        val stubbornStep by builder.define("stubbornStep", true)
        val infectiousMalice by builder.define("infectiousMalice", true)
        val iSeeYouNow by builder.define("iSeeYouNow", true)
        val maliceOutbreak by builder.define("maliceOutbreak", true)
        val perceivedMalice by builder.define("perceivedMalice", true)
        val vengeance by builder.define("vengeance", true)
        val backAndFill by builder.define("backAndFill", true)
        val agonyScreamer by builder.define("agonyScreamer", true)
        val cuttingWatermelonDream by builder.define("cuttingWatermelonDream", true)
        val insanePoet by builder.define("insanePoet", true)
        val paperBrain by builder.define("paperBrain", true)
        val shockTherapy by builder.define("shockTherapy", true)
        val burningPhobia by builder.define("burningPhobia", true)
        val constrainedHeart by builder.define("constrainedHeart", true)
        val drowningPhobia by builder.define("drowningPhobia", true)
        val piercingFever by builder.define("piercingFever", true)
        val destructionWorship by builder.define("destructionWorship", true)
        val prayerOfPain by builder.define("prayerOfPain", true)
        val freshRevenge by builder.define("freshRevenge", true)
        val hatredBloodline by builder.define("hatredBloodline", true)
        val outrageousSpirit by builder.define("outrageousSpirit", true)
        val resentfulSoul by builder.define("resentfulSoul", true)
        val tooResentfulToDie by builder.define("tooResentfulToDie", true)
        val morirsDeathwish by builder.define("morirsDeathwish", true)
        val morirsLifebound by builder.define("morirsLifebound", true)
        val guidensRegret by builder.define("guidensRegret", true)
        val lastSweetDream by builder.define("lastSweetDream", true)
        val necessaryEvil by builder.define("necessaryEvil", true)
        val survivalRuse by builder.define("survivalRuse", true)
        val survivalShortcut by builder.define("survivalShortcut", true)
        val corruptedKindred by builder.define("corruptedKindred", true)
        val lightburnFungalParasitic by builder.define("lightburnFungalParasitic", true)
        val prototypeChaotic by builder.define("prototypeChaotic", true)
        val prototypeChaoticTypeBeta by builder.define("prototypeChaoticTypeBeta", true)
        val shadowborn by builder.define("shadowborn", true)
        val scholarOfOriginalSin by builder.define("scholarOfOriginalSin", true)
        val originalSinErosion by builder.define("originalSinErosion", true)
        val burialObject by builder.define("burialObject", true)
    }

    class ApplyOnEnchantingTableConfig(
        builder: ForgeConfigSpec.Builder
    ) {
        val anEnchantedGoldenAppleADay by builder.define("anEnchantedGoldenAppleADay", true)
        val deathPunk by builder.define("deathPunk", true)
        val exoticHealer by builder.define("exoticHealer", true)
        val savorTheTasted by builder.define("savorTheTasted", true)
        val trickster by builder.define("trickster", true)
        val covertKnife by builder.define("covertKnife", true)
        val enviousKind by builder.define("enviousKind", true)
        val eyesore by builder.define("eyesore", true)
        val sourceOfEnvy by builder.define("sourceOfEnvy", true)
        val thornInFlesh by builder.define("thornInFlesh", true)
        val cleansingBeforeUsing by builder.define("cleansingBeforeUsing", true)
        val comeBackAtDusk by builder.define("comeBackAtDusk", true)
        val dirtyMoney by builder.define("dirtyMoney", true)
        val pilferageCreed by builder.define("pilferageCreed", true)
        val carefullyIdentified by builder.define("carefullyIdentified", true)
        val nimbleFinger by builder.define("nimbleFinger", true)
        val regularCustomerProgram by builder.define("regularCustomerProgram", true)
        val armorUp by builder.define("armorUp", true)
        val frivolousStep by builder.define("frivolousStep", true)
        val miraculousEscape by builder.define("miraculousEscape", true)
        val potentialBurst by builder.define("potentialBurst", true)
        val stubbornStep by builder.define("stubbornStep", true)
        val infectiousMalice by builder.define("infectiousMalice", true)
        val iSeeYouNow by builder.define("iSeeYouNow", true)
        val maliceOutbreak by builder.define("maliceOutbreak", true)
        val perceivedMalice by builder.define("perceivedMalice", true)
        val vengeance by builder.define("vengeance", true)
        val backAndFill by builder.define("backAndFill", true)
        val agonyScreamer by builder.define("agonyScreamer", true)
        val cuttingWatermelonDream by builder.define("cuttingWatermelonDream", true)
        val insanePoet by builder.define("insanePoet", true)
        val paperBrain by builder.define("paperBrain", true)
        val shockTherapy by builder.define("shockTherapy", true)
        val burningPhobia by builder.define("burningPhobia", true)
        val constrainedHeart by builder.define("constrainedHeart", true)
        val drowningPhobia by builder.define("drowningPhobia", true)
        val piercingFever by builder.define("piercingFever", true)
        val destructionWorship by builder.define("destructionWorship", true)
        val prayerOfPain by builder.define("prayerOfPain", true)
        val freshRevenge by builder.define("freshRevenge", true)
        val hatredBloodline by builder.define("hatredBloodline", true)
        val outrageousSpirit by builder.define("outrageousSpirit", true)
        val resentfulSoul by builder.define("resentfulSoul", true)
        val tooResentfulToDie by builder.define("tooResentfulToDie", true)
        val morirsDeathwish by builder.define("morirsDeathwish", true)
        val morirsLifebound by builder.define("morirsLifebound", true)
        val guidensRegret by builder.define("guidensRegret", true)
        val lastSweetDream by builder.define("lastSweetDream", true)
        val necessaryEvil by builder.define("necessaryEvil", true)
        val survivalRuse by builder.define("survivalRuse", true)
        val survivalShortcut by builder.define("survivalShortcut", true)
        val corruptedKindred by builder.define("corruptedKindred", true)
        val lightburnFungalParasitic by builder.define("lightburnFungalParasitic", true)
        val prototypeChaotic by builder.define("prototypeChaotic", true)
        val prototypeChaoticTypeBeta by builder.define("prototypeChaoticTypeBeta", true)
        val shadowborn by builder.define("shadowborn", true)
        val scholarOfOriginalSin by builder.define("scholarOfOriginalSin", true)
        val originalSinErosion by builder.define("originalSinErosion", true)
        val burialObject by builder.define("burialObject", true)
    }

    class IsTreasureConfig(
        builder: ForgeConfigSpec.Builder
    ) {
        val anEnchantedGoldenAppleADay by builder.define("anEnchantedGoldenAppleADay", false)
        val deathPunk by builder.define("deathPunk", false)
        val exoticHealer by builder.define("exoticHealer", false)
        val savorTheTasted by builder.define("savorTheTasted", false)
        val trickster by builder.define("trickster", false)
        val covertKnife by builder.define("covertKnife", false)
        val enviousKind by builder.define("enviousKind", false)
        val eyesore by builder.define("eyesore", true)
        val sourceOfEnvy by builder.define("sourceOfEnvy", false)
        val thornInFlesh by builder.define("thornInFlesh", false)
        val cleansingBeforeUsing by builder.define("cleansingBeforeUsing", true)
        val comeBackAtDusk by builder.define("comeBackAtDusk", true)
        val dirtyMoney by builder.define("dirtyMoney", true)
        val pilferageCreed by builder.define("pilferageCreed", true)
        val carefullyIdentified by builder.define("carefullyIdentified", false)
        val nimbleFinger by builder.define("nimbleFinger", false)
        val regularCustomerProgram by builder.define("regularCustomerProgram", true)
        val armorUp by builder.define("armorUp", false)
        val frivolousStep by builder.define("frivolousStep", false)
        val miraculousEscape by builder.define("miraculousEscape", false)
        val potentialBurst by builder.define("potentialBurst", false)
        val stubbornStep by builder.define("stubbornStep", false)
        val infectiousMalice by builder.define("infectiousMalice", false)
        val iSeeYouNow by builder.define("iSeeYouNow", false)
        val maliceOutbreak by builder.define("maliceOutbreak", false)
        val perceivedMalice by builder.define("perceivedMalice", false)
        val vengeance by builder.define("vengeance", false)
        val backAndFill by builder.define("backAndFill", false)
        val agonyScreamer by builder.define("agonyScreamer", false)
        val cuttingWatermelonDream by builder.define("cuttingWatermelonDream", true)
        val insanePoet by builder.define("insanePoet", false)
        val paperBrain by builder.define("paperBrain", false)
        val shockTherapy by builder.define("shockTherapy", false)
        val burningPhobia by builder.define("burningPhobia", false)
        val constrainedHeart by builder.define("constrainedHeart", false)
        val drowningPhobia by builder.define("drowningPhobia", false)
        val piercingFever by builder.define("piercingFever", false)
        val destructionWorship by builder.define("destructionWorship", false)
        val prayerOfPain by builder.define("prayerOfPain", false)
        val freshRevenge by builder.define("freshRevenge", false)
        val hatredBloodline by builder.define("hatredBloodline", false)
        val outrageousSpirit by builder.define("outrageousSpirit", false)
        val resentfulSoul by builder.define("resentfulSoul", true)
        val tooResentfulToDie by builder.define("tooResentfulToDie", true)
        val morirsDeathwish by builder.define("morirsDeathwish", true)
        val morirsLifebound by builder.define("morirsLifebound", true)
        val guidensRegret by builder.define("guidensRegret", true)
        val lastSweetDream by builder.define("lastSweetDream", true)
        val necessaryEvil by builder.define("necessaryEvil", false)
        val survivalRuse by builder.define("survivalRuse", false)
        val survivalShortcut by builder.define("survivalShortcut", false)
        val corruptedKindred by builder.define("corruptedKindred", false)
        val lightburnFungalParasitic by builder.define("lightburnFungalParasitic", true)
        val prototypeChaotic by builder.define("prototypeChaotic", false)
        val prototypeChaoticTypeBeta by builder.define("prototypeChaoticTypeBeta", false)
        val shadowborn by builder.define("shadowborn", false)
        val scholarOfOriginalSin by builder.define("scholarOfOriginalSin", true)
        val originalSinErosion by builder.define("originalSinErosion", true)
        val burialObject by builder.define("burialObject", false)
    }
}