kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47.2,)
loader_version_range=[4.11,)
kff_version=4.11.0

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=flowingagony_reborn
mod_name=FlowingAgonyReborn
mod_version=1.1.0
mod_description=Among the countless arts of the endless world, the art born from agony and suffering has always come from the darkest times.\nNow the Marble Gate brings this art from an unknown dimension to the present world. There is no end to the suffering in this world, and no one can turn back from walking in the long flowing river of agony.
mod_authors=Error1015
mod_license=BSD 3-Clause
mod_group_id=love.marblegate.flowingagonyreborn